version: '2'

services:

  app:
    build:
      context: .
      args:
        RAILS_ROOT: /app
        APP_SRC: ${APP_SRC}
    volumes:
      - app_vol:/app
    ports:
      - "3000"
    links:
      - db
    environment:
      - SQL_PW=${SQL_PW}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    depends_on:
      - db
  nginx:
    build:
      context: ./docker/nginx/
      args:
        RAILS_ROOT: /app
    links:
      - app
    depends_on:
      - app
    volumes:
      - app_vol:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PW}
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
volumes:
  app_vol: