version: '2'

services:

  mailslave:
    build:
      context: .
      dockerfile: ./docker/mailslave/Dockerfile
      args:
        RAILS_ROOT: /app
        APP_SRC: ${APP_SRC}
    volumes:
      - mailslave_storage:/app/storage
      - mailslave_logs:/app/log
      - ./docker/mailslave/logrotate/mailslave:/etc/logrotate.d/mailslave
      - ./docker/mailslave/cron/mailslave_cron:/etc/cron.daily/mailslave.cron
    ports:
      - "3000"
    links:
      - mailslave_db
    environment:
      - SQL_PW=${SQL_PW}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - mailslave_db
  mailslave_nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        RAILS_ROOT: /app
    links:
      - mailslave
    depends_on:
      - mailslave
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
  mailslave_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PW}
    volumes:
      - mailslave_sql:/var/lib/mysql
      - ./docker/db/mycnf.cnf:/etc/mysql/conf.d/mycnf.cnf
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - mailslave_db
volumes:
  mailslave_storage:
  mailslave_logs:
  mailslave_sql: